services:
    breaking_bet.bet.update.service.transactional:
        class: BreakingBetBundle\Internal\Service\Transactional
        arguments:
            - '@breaking_bet.bet.update.service'
            - '@doctrine.orm.entity_manager'
            - '@logger'

    breaking_bet.bet.update.service:
        class: BreakingBetBundle\Operation\Bet\Update\Service\Service
        arguments:
            - '@breaking_bet.bet.update.remote_call'
            - '@breaking_bet.bet.update.data_updater'
            - '@logger'

    breaking_bet.bet.update.remote_call:
        class: BreakingBetBundle\Interaction\RemoteCall\RemoteCall
        arguments:
            - '@breaking_bet.bet.update.request_assembler'
            - '@breaking_bet.guzzle.client'
            - '@breaking_bet.bet.update.data_parser.chain'
            - '@breaking_bet.object_builder.jms'
            - '@breaking_bet.bet.update.response_factory'
            - '@validator'
            - '@logger'

    breaking_bet.bet.update.request_assembler:
        class: BreakingBetBundle\Operation\Bet\Update\RequestAssembler\RequestAssembler
        arguments:
            - 'GET'

    breaking_bet.bet.update.response_factory:
        class: BreakingBetBundle\Operation\Bet\Update\Dto\Response\SuccessfulResponseFactory

    breaking_bet.bet.update.data_parser.chain:
        class: BreakingBetBundle\Internal\DataParser\Chain
        arguments:
            -
                - '@breaking_bet.bet.update.betsbc.data_parser'

    breaking_bet.bet.update.data_updater:
        class: BreakingBetBundle\Operation\Bet\Update\DataUpdater\DataUpdater
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@breaking_bet.entity.repository.factory'
            - '@logger'