controller.api.drawdown.get:
    path: '/api/v1/drawdown/get'
    defaults: { _controller: controller.api:operationAction, security: false }
    methods: [POST]

controller.main.home:
    path: '/'
    defaults: { _controller: controller.main:homeAction, security: false }
    methods: [GET]
