controller.api.bet.get:
    path: '/api/bet/get'
    defaults: { _controller: controller.api:operationAction, security: false }
    methods: [POST]

controller.main.home:
    path: '/'
    defaults: { _controller: controller.main:homeAction, security: false }
    methods: [GET]
