export default
'<td>:sport</td>' +
'<td>:chain</td>' +
'<td>:event</td>' +
'<td>:actual_p1</td>' +
'<td>:actual_p2</td>' +
'<td>:actual_x</td>' +
'<td>:double_1x</td>' +
'<td>:double_x2</td>' +
'<td>:double_12</td>' +
'<td>:handicap_kf_f1</td>' +
'<td>:handicap_f2</td>' +
'<td>:handicap_kf_f2</td>' +
'<td>:handicap_f2</td>' +
'<td>:total</td>' +
'<td>:total_under</td>' +
'<td>:total_over</td>' +
'<td>:actual_y</td>' +
'<td>:actual_n</td>'