services:
    bets.update:
      class: AppBundle\Command\BetUpdateCommand
      arguments:
        - '@service.parser'
        - '@logger'
      tags:
        - { name: console.command }

    bets.notify:
      class: AppBundle\Command\BetNotifyCommand
      arguments:
          - '@breaking_bet.operation.bet.get.service'
          - '@logger'
