services:
    breaking_bet.object_builder.jms:
        class: AppBundle\Internal\ObjectBuilder\JMSObjectBuilder
        arguments:
            - '@jms_serializer'
            - '@logger'

    breaking_bet.interaction.data_extractor.assert_decorator:
        class: AppBundle\Interaction\DataExtractor\AssertDataExtractorDecorator
        arguments:
            - '@breaking_bet.interaction.data_extractor.http_request.composite'
            - 'Symfony\Component\HttpFoundation\Request'

    breaking_bet.interaction.data_extractor.http_request.composite:
        class: AppBundle\Interaction\DataExtractor\DataExtractorComposite
        arguments:
            -
                - '@breaking_bet.interaction.data_extractor.http_request.json'
                - '@breaking_bet.interaction.data_extractor.http_request.url'

    breaking_bet.interaction.data_extractor.http_request.json:
        class: AppBundle\Interaction\DataExtractor\Request\JsonDataExtractor

    breaking_bet.interaction.data_extractor.http_request.post:
        class: AppBundle\Interaction\DataExtractor\Request\PostDataExtractor

    breaking_bet.interaction.data_extractor.http_request.get:
        class: AppBundle\Interaction\DataExtractor\Request\GetDataExtractor

    breaking_bet.interaction.data_extractor.http_request.url:
        class: AppBundle\Interaction\DataExtractor\Request\UrlDataExtractor
        arguments:
            - '@router'

    breaking_bet.interaction.api_to_http_transformer:
        class: AppBundle\Interaction\Transformer\Response\Transformer
        arguments:
            - '@breaking_bet.interaction.object_to_array_transformer'

    breaking_bet.interaction.object_to_array_transformer:
        class: AppBundle\Interaction\Transformer\Type\ObjectToArrayTransformer

    breaking_bet.entity.repository.factory:
        class: AppBundle\Entity\Repository\RepositoryFactory
        arguments:
            - '@doctrine.orm.entity_manager'
