services:
    controller.api:
        class: AppBundle\Controller\ApiController
        arguments:
            - '@breaking_bet.operation.bet.get.http_to_api_transformer'
            - '@validator'
            - '@breaking_bet.operation.bet.get.service'
            - '@breaking_bet.operation.bet.get.api_to_http_transformer'
            - '@logger'

    controller.main:
        class: AppBundle\Controller\MainController
        arguments:
            - '@service_container'