services:
    controller.api:
        class: AppBundle\Controller\ApiController
        arguments:
            - '@service.parser'
    service.parser:
        class: AppBundle\Service\Parser\Parser
        arguments:
            - '@service.parser.external.factory'
    service_config:
        class: AppBundle\ServiceConfig\ServiceConfig
        arguments:
            - '%service_configuration%'
    interaction.protocol:
        class: AppBundle\Interaction\Protocol\Protocol
        arguments:
            - '@guzzle.client'
    guzzle.client:
        class: GuzzleHttp\Client
    service.parser.external.factory:
        class: AppBundle\Service\Parser\External\Factory\Factory
        arguments:
            - '@service_config'
            - '@service_container'
    parser.external.assembler.betbc:
        class: AppBundle\Service\Parser\External\Betsbc\Assembler\Assembler
        arguments:
            - '@service_config'
    parser.external.resolver.betbc:
        class: AppBundle\Service\Parser\External\Betsbc\Resolver\Resolver
        arguments:
            - '@data_migrator.factory'
            - '@helper.finder'
    parser.external.data_provider.betbc:
        class: AppBundle\Service\Parser\External\Betsbc\DataProvider\DataProvider
        arguments:
            - '@parser.external.assembler.betbc'
            - '@interaction.protocol'
            - '@service_config'
    data_migrator.factory:
        class: AppBundle\DataMigrator\Factory\DataMigratorFactory
        arguments:
            - '@service_container'
    helper.finder:
        class: AppBundle\Helper\Finder\Finder


