services:
    breaking_bet.object_builder.jms:
        class: BreakingBetBundle\Internal\ObjectBuilder\JMSObjectBuilder
        arguments:
            - '@jms_serializer'
            - '@logger'

    breaking_bet.interaction.api_to_http_transformer:
        class: BreakingBetBundle\Interaction\Transformer\Response\Transformer
        arguments:
            - '@breaking_bet.interaction.object_to_array_transformer'

    breaking_bet.interaction.object_to_array_transformer:
        class: BreakingBetBundle\Interaction\Transformer\Type\ObjectToArrayTransformer

    breaking_bet.entity.repository.factory:
        class: BreakingBetBundle\Entity\Repository\RepositoryFactory
        arguments:
            - '@doctrine.orm.entity_manager'