services:
    bets.update:
        class: BreakingBetBundle\Command\Bet\Update
        arguments:
            - '@service.parser'
            - '@logger'
        tags:
            - { name: console.command }
