services:
    breaking_bet.guzzle.client:
        class: GuzzleHttp\Client

    breaking_bet.guzzle.tor.client:
        class: GuzzleHttp\Client
        arguments:
            -
                handler: '@breaking_bet.guzzle.tor.stack'

    breaking_bet.guzzle.tor.stack:
        class: BreakingBetBundle\Interaction\Guzzle\TorHandlerStack
        calls:
            -
                method: setHandler
                arguments:
                    - '@breaking_bet.guzzle.curl_handler'

    breaking_bet.guzzle.curl_handler:
        class: GuzzleHttp\Handler\CurlHandler

    breaking_bet.object_builder.jms:
        class: BreakingBetBundle\Internal\ObjectBuilder\JMSObjectBuilder
        arguments:
            - '@jms_serializer'
            - '@logger'

    breaking_bet.interaction.api_to_http_transformer:
        class: BreakingBetBundle\Interaction\Transformer\Response\Json
        arguments:
            - '@jms_serializer'

    breaking_bet.entity.repository.factory:
        class: BreakingBetBundle\Entity\Repository\RepositoryFactory
        arguments:
            - '@doctrine.orm.default_entity_manager'

    breaking_bet.data_extractor.blank:
        class: BreakingBetBundle\Internal\DataExtractor\Blank

    breaking_bet.payload_modifier.blank:
        class: BreakingBetBundle\Internal\PayloadModifier\Blank

    breaking_bet.payload_modifier.json:
        class: BreakingBetBundle\Internal\PayloadModifier\Json

    breaking_bet.data_extractor.array_from_json_request:
        class: BreakingBetBundle\Interaction\DataExtractor\HttpRequest\Content
        arguments:
            - '@breaking_bet.data_extractor.blank'
            - '@breaking_bet.payload_modifier.json'