services:
    bets.update:
        class: BreakingBetBundle\Command\BetUpdateCommand
        arguments:
            - '@service.parser'
            - '@logger'
        tags:
            - { name: console.command }
