parameters:
    service_configuration:
        betsbc:
            base_url: 'http://www.betsbc.com/api/v1/bets/line'
            proxy:
                ip: '89.107.58.215'
                port: '443'
            service_name: 'betbc'
            query_parameters_map:
                rev: '5'
                ext: '0'
                lng: '1'