services:
    service_config:
        class: BreakingBetBundle\ServiceConfig\ServiceConfig
        arguments:
            - '%service_configuration%'

    interaction.protocol:
        class: BreakingBetBundle\Interaction\Protocol\Protocol
        arguments:
            - '@guzzle.client'

    guzzle.client:
        class: GuzzleHttp\Client