services:
    breaking_bet.operation.bet.get.service:
        class: BreakingBetBundle\Operation\Bet\Get\Service\Service
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@breaking_bet.entity.repository.factory'
            - '@logger'

    breaking_bet.operation.bet.get.http_to_api_transformer:
        class: BreakingBetBundle\Interaction\Transformer\Request\Transformer
        arguments:
            - '@breaking_bet.object_builder.jms'
            - '@breaking_bet.operation.bet.get.request_factory'
            - '@breaking_bet.interaction.data_extractor.assert_decorator'

    breaking_bet.operation.bet.get.request_factory:
        class: BreakingBetBundle\Operation\Bet\Get\Dto\Request\ApiRequestFactory